### ISSUE TITLE
TypeError: hog() got an unexpected keyword argument 'visualise'

### ISSUE THREAD

**Issue by sivanaikk** [apgeorg/self-driving-car-vehicle-detection#1]
When I run this playbook. It is showing an error :  TypeError: hog() got an unexpected keyword argument 'visualise' at line 7 and line 23 in file /utils/utils.py
![issue](https://user-images.githubusercontent.com/60335740/103679674-285b3500-4fab-11eb-987a-18e3e459ba9b.png)

**Comment by apgeorg** [comment]
Hi, there! Issue is fixed. 

Please check as well: https://scikit-image.org/docs/stable/api/skimage.feature.html

**Comment by sivanaikk** [comment]
I changed visualise to visualize( ). **It worked !**
